#!/bin/bash

dir="$(dirname "$0")"

function check_dependencies {
	_install_ppas "$dir/data/ppa.list"

	_check_packages "$dir/data/packages.post-install-script-dependencies.list"
}

function _check_packages {
	show_info "Checking packages from file" $1

	for package in $(cat $1); do

		PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $package | grep "install ok installed")

		if [ "" == "$PKGCHECK" ]; then
			show_info $package 'is not installed. Proceeding'
			show_warning 'Requires root privileges'

			sudo apt-get -y install $package

			_check_fail $?
		fi

		show_success "Dependency '$package' is installed."
	done

	show_info "Proceeding."
}

function _check_fail {
	EXITSTATUS=$1
	if [[ $EXITSTATUS != 0 ]]; then
		show_error "Something may have went wrong during the last command. Returning."
		sleep 3s
	fi
}

function _check_fail_go_main {
	EXITSTATUS=$1
	if [[ $EXITSTATUS != 0 ]]; then
		show_error "Something may have went wrong during the last command. Returning."
		sleep 3s && main
	fi
}

function _install_ppas {
	show_info "Installing ppa dependencies..."

	for ppa in $(cat $1); do
		PPACHECK=$(grep ^ /etc/apt/sources.list /etc/apt/sources.list.d/* | grep $ppa)

		if [ "" == "$PPACHECK" ]; then
			show_info "Adding ppa '$ppa'"
			show_warning 'Requires root privileges'

			sudo add-apt-repository -y -u $ppa && _check_fail $?
		else
			show_success "PPA '$ppa' exists."
		fi
	done
}