#!/bin/bash

# Main
function main {
	eval `resize`
	MAIN=$(whiptail \
		--notags \
		--title "Ubuntu Post-Install Script" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Quit" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		menu_thirdparty 'Select apps to install' \
		3>&1 1>&2 2>&3)

	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		$MAIN
	else
		quit
	fi
}

# Quit
function quit {
	if (whiptail --title "Quit" --yesno "Are you sure you want quit?" 10 60) then
		echo "Exiting..."
		show_info 'Thanks for using!'
		exit 99
	else
		main
	fi
}
