#!/bin/bash

dir="$(dirname "$0")"

source $dir/third-party/dropbox
source $dir/third-party/fontforge
source $dir/third-party/google-chrome
source $dir/third-party/inkscape
source $dir/third-party/keybase
source $dir/third-party/minecraft
source $dir/third-party/oracle-java
source $dir/third-party/rvm
source $dir/third-party/slack
source $dir/third-party/synergy
source $dir/third-party/spotify
source $dir/third-party/steam
source $dir/third-party/sublime-text
source $dir/third-party/vlc
source $dir/third-party/virtual-box

# Install Third-Party Applications
function thirdparty {
    eval `resize`

    THIRDPARTY=$(whiptail \
        --title "Third-Party Installation" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        --checklist "\nWhat third-party software would you like to install?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        "dropbox"           "Dropbox" OFF \
        "fontforge"         "FontForge" OFF \
        "google-chrome"     "Google Chrome" OFF \
        "inkscape"          "Inkscape" OFF \
        "keybase"           "Keybase" OFF \
        "minecraft"         "Minecraft" OFF \
        "oracle-java"       "Oracle Java" OFF \
        "rvm"               "Ruby Version Manager (RVM)" OFF \
        "slack"             "Slack" OFF \
        "spotify"           "Spotify" OFF \
        "steam"             "Steam" OFF \
        "synergy"           "Synergy" OFF \
        "sublime-text"      "Sublime Text 3" OFF \
        "vlc"               "VLC Player" OFF \
        "virtualbox"        "Virtual Box" OFF \
        3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        for package in $THIRDPARTY; do
            $(echo $package | cut -d'"' -f 2)
        done;
    else
        main
    fi
}